image: node:16

stages:
    - npm
    - build
    - test
    - stage
    - prod

npm:
    stage: npm
    only:
        - merge_requests

    script:
        - npm config set registry ${CI_NPM_REGISTRY}
        - npm ci
    cache:
        paths:
            - node_modules/
    artifacts:
        expire_in: 1 days
        when: on_success
        paths:
            - node_modules/

build:
    stage: build
    only:
        - merge_requests
    dependencies:
        - npm
    script:
        - npm run build

test:
    stage: test
    only:
        - merge_requests

    dependencies:
        - npm
    script:
        - npm test
        - npm run test

Deploy-to-Stage:
    stage: stage
    script:
        - bash deploy/stage_deploy.sh
    rules:
        - if: $CI_COMMIT_BRANCH == "dev"
    environment:
        name: staging

Deploy-to-Prod:
    stage: prod
    when: manual
    allow_failure: false
    script:
        - bash deploy/prod_deploy.sh
    rules:
        - if: $CI_COMMIT_BRANCH == "main"
    environment:
        name: prod
