version: "3.1"
services:
    db:
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cc_event
        ports:
            - "3307:3306"
        command: ["mysqld", "--character-set-server=latin1", "--collation-server=latin1_swedish_ci"]
